name: Django CI

on:
  push:
    branches: [ V3.6.X ]
  pull_request:
    branches: [ V3.6.X ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        # prepare env
        source scripts/develop/sites/community/env.sh
        # add local_settings.py
        echo '# -*- coding: utf-8 -*-
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": "db.sqlite3",
            }
        }

        LOG_LEVEL = "DEBUG"

        BK_IAM_SKIP = 1' > local_settings.py
        # run unittest
        python manage.py test
